version: "3.8"

services:
  programmeerimine2:
    build: .
    ports: 
      - 80:80
    environment:
      PORT: 80
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: programmeerimine2

volumes:
  mysql-data: